### ISSUE TITLE
MD3/IQM meshes instead of sprites for players/entities?

### ISSUE THREAD

**Issue by VinnyVicious** [IgeNiaI/Q-Zandronum#248]
Does the engine allow for mesh replacements for sprites of players and entities? If it does, what are the supported formats? Is there a guide on how to do it? Is there a specific path that files should be placed, or a custom WAD editor?

**Comment by IgeNiaI** [comment]
Q-Zandronum has the same support for 3d models as vanilla Zandronum. I am not familiar with it and I couldn't google any tutorials. At least you can see the supported formats at https://zdoom.org/wiki/Model_format and some info on how to add it at https://zdoom.org/wiki/MODELDEF

**Comment by VinnyVicious** [comment]
Thank you for the info, really appreciate it!
