### ISSUE TITLE
Possible to fix running mods from folder?

### ISSUE THREAD

**Issue by Velaron** [IgeNiaI/Q-Zandronum#271]
I like to run my mods from a folder instead of an archive, because it saves a lot of time repackaging everything and is easier for source control. With latest GZDoom builds using `gzdoom.exe -file E:\MyModFolder\` works perfectly fine, but Zandronum spits different errors about not finding files:
`Script error, ":ANIMDEFS" line 2:
Unknown texture FHDS01`
Sounds like the order of loading the lumps is broken when using folders or something, possible to fix?

**Comment by IgeNiaI** [comment]
I'll take a look but can't promise anything

**Comment by IgeNiaI** [comment]
Yes it was reverted because it broke loading directories on Linux.
What is your use case? Are you on Windows or Linux?

**Comment by Velaron** [comment]
I'm running my mod from a folder on Windows, and it's kinda huge right now so repacking it every time before running is very slow, and SLADE often corrupts the archive when saving

**Comment by IgeNiaI** [comment]
How does converting path to lowercase fix it though?

**Comment by Velaron** [comment]
> How does converting path to lowercase fix it though?

Not sure to be honest, I just found that in GZDoom commit history

https://github.com/ZDoom/gzdoom/commit/a16f92c508d3b19d9c540a5d11356d9518e60538

**Comment by IgeNiaI** [comment]
Try this build
[q-zandronum.zip](https://github.com/IgeNiaI/Q-Zandronum/files/11433055/q-zandronum.zip)

**Comment by IgeNiaI** [comment]
Thanks. I'll wait for the other guy to test his scenario on Linux.

**Comment by IgeNiaI** [comment]
Looks like it's fixed for both use cases
