### ISSUE TITLE
Some of the text is stretched out in HUD.

### ISSUE THREAD

**Issue by insellium** [IgeNiaI/Q-Zandronum#294]
It doesn't look good to me.
https://imgur.com/a/WDRggKY

**Comment by IgeNiaI** [comment]
What is your screen resolution?
How does it look in GZDoom and vanilla Zandronum?

**Comment by insellium** [comment]
1) 1920x1080
2.1) Zandronum (CDI via GZDOOM doesn't start) - https://imgur.com/a/UYBs3Hf

**Comment by IgeNiaI** [comment]
Is it on Zandronum 3.1 or 3.0? Q-Zandronum is based on the latter and I don't know if they changed anything related to text in 3.1
Anyway, you seem to have text scaling enabled. Try going to Options -> Hud options -> Message Options -> Text Scaling and disable text scaling in there.

**Comment by insellium** [comment]
Ah. It's worked. Thanks. (I didn't notice this item in the settings menu).

**Comment by IgeNiaI** [comment]
Nice
