### ISSUE TITLE
Unknown command "compat_clientssendfullbuttoninfo" in MM8BDM

### ISSUE THREAD

**Issue by insellium** [IgeNiaI/Q-Zandronum#295]
https://imgur.com/a/7GM1Jrw
Is there any way to remove this message?

**Comment by IgeNiaI** [comment]
You need to remove it from the mod you are playing. Q-Zandronum always sends full button info, so this cvar is removed and that's why you get this message.

**Comment by insellium** [comment]
One last thing related to MM8BDM that I noticed.
In the archive with the mod, in the default.ini file is the parameter "compat_skulltagjumping=true", which blocks the ability to jump (if you run the mod through Q-Zandronum). Solves this by changing the parameter from "true" to "false".

**Comment by IgeNiaI** [comment]
I'll investigate that, thanks

**Comment by insellium** [comment]
Nice

**Comment by IgeNiaI** [comment]
Thanks for bug report, it will be fixed in 1.3 release
