### ISSUE TITLE
Switch states are not syncronized

### ISSUE THREAD

**Issue by Alexander230** [IgeNiaI/Q-Zandronum#326]
When in coop one player presses a switch, other players still see it in the previous state, and can still "press" it (with no effect).

**Comment by IgeNiaI** [comment]
Do you remember what mods and maps you played? Looks like default doom 2 switches work fine.

**Comment by Alexander230** [comment]
We played default doom 2 without mods. Switches work, but next players can "press" one-time switches for the second time, without any effect.

**Comment by Alexander230** [comment]
Made an experiment in MAP01. 1st player presses, switch picture updated for both players. 2nd player presses again, hears sound of the switch, and picture updates only for the 2nd player. After that, both players can't press it.
