### ISSUE TITLE
Mac version crashes in large maps

### ISSUE THREAD

**Issue by Alexander230** [IgeNiaI/Q-Zandronum#328]
The game crashes when trying to load some large maps (MAP02 and MAP03 from Lost Civilization, some maps from Ancient Aliens, probably 12 and 13; also large maps generated by Obsidian). It happens only in Mac version; on Windows and Linux the same maps work fine. Launching these maps on Mac with Windows executable and Wine also works fine. This problem presents in both Q-Zandronum and upstream Zandronum.

**Comment by IgeNiaI** [comment]
Do you have the crash log by any chance?

**Comment by Alexander230** [comment]
Are there detailed logs somewhere? I've tried to launch the game from console, but there is only 1 error message after trying to load the map:

zsh: segmentation fault  /Applications/Q-Zandronum.app/Contents/MacOS/q-zandronum -iwad   -file  -warp

**Comment by IgeNiaI** [comment]
I don't know, the mac version isn't even compiled by me. I'll ask around.

**Comment by doomjoshuaboy** [comment]
> Are there detailed logs somewhere? I've tried to launch the game from console, but there is only 1 error message after trying to load the map:
> 
> zsh: segmentation fault /Applications/Q-Zandronum.app/Contents/MacOS/q-zandronum -iwad -file -warp

did you see more info button it should give you the crashlogs?

**Comment by Alexander230** [comment]
[log.txt](https://github.com/IgeNiaI/Q-Zandronum/files/12645887/log.txt)

Found it in MacOS window that pops up after crash

**Comment by doomjoshuaboy** [comment]
[Q-Zandronumtest.app.zip](https://github.com/IgeNiaI/Q-Zandronum/files/12654198/Q-Zandronumtest.app.zip)

try this build here

**Comment by Alexander230** [comment]
It worked, thank you! There was an error in the console, but the map loaded succesfully:

Cannot open nodes file /Library/Application Support/zdoom/cache/joi_lstcv15.wad/MAP03.gzc for writing

**Comment by IgeNiaI** [comment]
Nice! I'll include it in next release then.
