### ISSUE TITLE
Latest versions for Windows/Linux and Mac differ, so they can't play with each other

### ISSUE THREAD

**Issue by Alexander230** [IgeNiaI/Q-Zandronum#329]
Please include Mac version to 1.4.6 release; now 1.4.5 client can't connect to 1.4.6 servers, and also 1.4.6 contains an important crash fix for Mac.

**Comment by IgeNiaI** [comment]
We can't compile it for mac anymore, they changed something again...

**Comment by Alexander230** [comment]
Maybe there are workarounds for it, like virtual machine with older Mac OS, or cross compiling on Linux? GZdoom developers somehow managed to compile the new version for Mac.

**Comment by IgeNiaI** [comment]
GZDoom source code is way more up to date compared to Zandronum. It's possible, but requires time fixing the code.

**Comment by doomjoshuaboy** [comment]
@Alexander230 I am the one who build macOS binarires but i've just managed to fix this by building it from the latest sdk.

**Comment by Alexander230** [comment]
Nice, thank you!

**Comment by IgeNiaI** [comment]
The build is now uploaded to both github and qzan website

**Comment by Alexander230** [comment]
Thank you! :-)
