### ISSUE TITLE
Unknown player class error

### ISSUE THREAD

**Issue by Alexander230** [IgeNiaI/Q-Zandronum#331]
I've encountered this error in the console when tried to run a map "Bury My Heart Knee Deep":

Unknown player class 'NoJumpPlayerPawn'

Execution could not continue.

No player classes defined

Tested it, the same error appears in upstream Zandronum, but in GZDoom, DSDA and Crispy the map works fine.

**Comment by IgeNiaI** [comment]
The map defines the "NoJumpPlayerPawn" in ZScript, which is not supported by Q-Zandronum and Zandronum at all. That makes the map GZDoom and it's forks exclusive.
The issue should be fixed on map side.
