### ISSUE TITLE
Changing shaders in the engine (added in 1.4.15) breaks Ray Mohawk mods

### ISSUE THREAD

**Issue by Alexander230** [IgeNiaI/Q-Zandronum#340]
Please make this feature optional: now in Ray Mohawk 1 and 2 all sprites are displayed from IWAD instead of the mod.

**Comment by IgeNiaI** [comment]
It's not related to shaders. Anyway, I'll fix it in next version.

**Comment by IgeNiaI** [comment]
Should be fixed in next release. Feel free to reopen this ticket if it's not.

**Comment by Alexander230** [comment]
Nice, thank you!
