### ISSUE TITLE
[macOS] No music by default

### ISSUE THREAD

**Issue by KAMiKAZOW** [IgeNiaI/Q-Zandronum#343]
The default Fluidsynth produces no music. I had to manually set it to OPL Emulation.

macOS Sequoia, Intel

**Comment by doomjoshuaboy** [comment]
Firstly thanks for reporting about the no music by default, Unfortunately you might need to change the soundfont manually as its inside the app, All you got to do is  go to sound options and set a soundfont from there or you can use the console to add one, `fluid_patchset` use this command to change it.

**Comment by IgeNiaI** [comment]
Looks like the default soundfont isn't reachable on mac. Honestly I don't know how to fix it.

**Comment by KAMiKAZOW** [comment]
> Honestly I don't know how to fix it.

Not a perfect fix but a workaround: Set the default to OPL Emulation until anybody finds a fix.

**Comment by IgeNiaI** [comment]
What happens if you set midi device to system?

**Comment by KAMiKAZOW** [comment]
OPL Emulation is the only thing that produces sound.

**Comment by IgeNiaI** [comment]
What if you set the soundfont path to `$PROGDIR/gm.sf2` when using fluidsynth?
After that you'll need to click "Restart sound" and then restart the map.

**Comment by KAMiKAZOW** [comment]
Worked even without restarting the map.

<img width="1280" alt="Screenshot 2024-10-08 at 22 35 58" src="https://github.com/user-attachments/assets/a207d3e6-8fae-45d9-a0bd-7c54c43704f2">

**Comment by IgeNiaI** [comment]
Ok so this one is figured out and fixed. Thanks for the report.

**Comment by KAMiKAZOW** [comment]
> Ok so this one is figured out and fixed.

There hasn't been a commit to the git repo in three weeks. Manually changing the soundfont is a workaround, not a bug fix.

**Comment by IgeNiaI** [comment]
The master branch represents latest release, so that if people want to build it themselves, they get a fully compatible build.
The bug is fixed in Develop branch and will be included in next release.
https://github.com/IgeNiaI/Q-Zandronum/commit/8b0a2e1feeeca1305917749386cd122ed71f6d90
